; Projet : lecture de 2 capteurs de pression 4-20mA via ADS1115 sur ESP32-S2 Mini
; A placer a la racine du dossier "capteurs-pression/" dans le depot GitHub

[env:lolin_s2_mini]
platform = espressif32
board = lolin_s2_mini
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit ADS1X15 @ ^2.5.0
